import { Link } from "wouter";
import { Layout } from "@/components/Layout";
import { ArrowLeft } from "lucide-react";

export default function Disclaimer() {
  return (
    <Layout>
      <div className="max-w-3xl mx-auto px-6 py-12">
        <Link href="/">
          <span className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary mb-8 cursor-pointer">
            <ArrowLeft className="w-4 h-4" /> Back to home
          </span>
        </Link>
        <h1 className="text-4xl font-display font-bold mb-8">AI Disclaimer</h1>
        <div className="prose prose-slate max-w-none text-muted-foreground">
          <p className="mb-4">VisionAI uses artificial intelligence to generate images and text.</p>
          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">Generated Content</h2>
          <p className="mb-4">The images generated by our AI are artistic interpretations based on your inputs. We do not guarantee that the images will perfectly represent real-world objects or people.</p>
          <h2 className="text-xl font-bold text-foreground mt-8 mb-4">Uniqueness</h2>
          <p className="mb-4">While our AI strives to create unique content, there is a possibility that similar inputs may result in similar outputs.</p>
        </div>
      </div>
    </Layout>
  );
}
